# ← これを書いた行は「コメント」になります。設定ファイルの中にメモを書き残したいときに使うと便利です。
# スクリーンショット(ウィンドウのスクショを撮影→ファイルに保存してファイルパスを送信)

# ↓ これを書くと「ここから特定のプロセッサーの設定をはじめるよ」という意味になります。
[[processors]]
# 「今回は "screenshot" タイプのプロセッサーを使うよ」という意味になります。
feature = "screenshot"
# 着信を受け取るチャンネル名
channel_from = "ss"
# 結果を出力するチャンネル名
channel_to = "ocr"
# スクショを撮影したいウィンドウのタイトルに含まれる文字列を記入します
# とりあえずシンプルな「メモ帳」などで試してみましょう。
# この設定項目では . ? * ( ) \ $ ^ などの文字は特別な用途(正規表現)で使われるので、よくわからなければ今はそうした文字が入らない設定を試してみましょう。
title_regex = "ここにキャプチャーしたいウィンドウのタイトルに含まれる文字列を記入します"
# スクショの保存先を指定します。
paths = [ "ss.png" ]

# OCR(画像認識→テキスト)
[[processors]]
channel_from = "ocr"
channel_to = "description"
feature = "ocr"
# 日本語の文字を読み取りたい場合は "ja_JP" 、USA英語なら "en_US" のように設定します。
lang = "ja_JP"
# 入力として Screenshot などチャンネルの前段階のプロセッサーが出力した内容を受け取りたい場合は true にします。
load_from_content = true
